"""empty message

Revision ID: 4ff2946aad0c
Revises: None
Create Date: 2015-12-30 20:00:56.815102

"""

# revision identifiers, used by Alembic.
revision = '4ff2946aad0c'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'city_ibfk_1', 'city', type_='foreignkey')
    op.drop_column('city', 'airport')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('airport', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'city_ibfk_1', 'city', 'airport', ['airport'], ['id'])
    ### end Alembic commands ###
